### ISSUE TITLE
Clearing issues when move or resize windows with -g opengl

### ISSUE THREAD

**Issue by trsh** [Kinc-Samples/DearImGui-Kinc#2]
Win 10, opengl, GTX 750 ti

https://imgur.com/lageHj6

**Comment by hamad-almamari** [comment]
This also happend to me when I was testing kinc framework.

**Comment by Paolo-Oliverio** [comment]
it should be the call to the viewport function removing it fixes this issue in my project.

**Comment by RobDangerous** [comment]
Had nothing to do with any viewports, OpenGL considers scissor-rects when doing clears - I now prevent that directly in Kinc's OpenGL-backend.
